package runner

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/vietrix/vbuild/internal/config"
)

func (r *Runner) writeModelCard(taskName string, task *config.Task, vars map[string]string, metrics map[string]float64, datasets []datasetEntry) error {
	if task == nil || task.ModelCard == nil {
		return nil
	}
	path := task.ModelCard.Path
	if path == "" {
		path = filepath.Join(".vbuild", "model_cards", sanitizePath(taskName)+".md")
	}
	path = r.resolvePath(expandVars(path, vars))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	content := ""
	if task.ModelCard.Template != "" {
		templatePath := r.resolvePath(expandVars(task.ModelCard.Template, vars))
		data, err := os.ReadFile(templatePath)
		if err != nil {
			return err
		}
		templateVars := cloneStringMap(vars)
		templateVars["TASK_NAME"] = taskName
		for key, value := range task.ModelCard.Metadata {
			templateVars[key] = value
		}
		for key, value := range metrics {
			templateVars["METRIC_"+strings.ToUpper(sanitizeEnvKey(key))] = fmt.Sprintf("%v", value)
		}
		for _, entry := range datasets {
			name := strings.ToUpper(sanitizeEnvKey(entry.Name))
			templateVars["DATASET_"+name+"_VERSION"] = entry.Version
			if entry.Path != "" {
				templateVars["DATASET_"+name+"_PATH"] = entry.Path
			}
		}
		content = expandVars(string(data), templateVars)
	} else {
		content = buildDefaultModelCard(taskName, task, metrics, datasets)
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func buildDefaultModelCard(taskName string, task *config.Task, metrics map[string]float64, datasets []datasetEntry) string {
	builder := strings.Builder{}
	title := taskName
	if task.ModelCard != nil && task.ModelCard.Metadata != nil {
		if name, ok := task.ModelCard.Metadata["name"]; ok && name != "" {
			title = name
		}
	}
	builder.WriteString("# " + title + "\n\n")
	builder.WriteString("## Overview\n\n")
	builder.WriteString(fmt.Sprintf("Generated by vbuild task `%s`.\n\n", taskName))
	if task.ModelCard != nil && len(task.ModelCard.Metadata) > 0 {
		builder.WriteString("## Metadata\n\n")
		keys := make([]string, 0, len(task.ModelCard.Metadata))
		for key := range task.ModelCard.Metadata {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			builder.WriteString(fmt.Sprintf("- %s: %s\n", key, task.ModelCard.Metadata[key]))
		}
		builder.WriteString("\n")
	}
	if len(datasets) > 0 {
		builder.WriteString("## Datasets\n\n")
		for _, entry := range datasets {
			builder.WriteString(fmt.Sprintf("- %s @ %s\n", entry.Name, entry.Version))
		}
		builder.WriteString("\n")
	}
	if len(metrics) > 0 {
		builder.WriteString("## Metrics\n\n")
		builder.WriteString("| Metric | Value |\n| --- | --- |\n")
		keys := make([]string, 0, len(metrics))
		for key := range metrics {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			builder.WriteString(fmt.Sprintf("| %s | %v |\n", key, metrics[key]))
		}
		builder.WriteString("\n")
	}
	return builder.String()
}
